apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.fastapi.name }}
  labels:
    app: {{ .Values.services.fastapi.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.services.fastapi.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.fastapi.name }}
    spec:
      containers:
      - name: {{ .Values.services.fastapi.name }}
        image: "{{ .Values.image.fastapi.repository }}:{{ .Values.image.fastapi.tag }}"
        imagePullPolicy: {{ .Values.image.fastapi.pullPolicy }}
        ports:
        - containerPort: {{ .Values.services.fastapi.targetPort }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configMap.fastapi }}
        resources:
          limits:
            cpu: {{ .Values.resources.fastapi.limits.cpu }}
            memory: {{ .Values.resources.fastapi.limits.memory }}
          requests:
            cpu: {{ .Values.resources.fastapi.requests.cpu }}
            memory: {{ .Values.resources.fastapi.requests.memory }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.services.fastapi.targetPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.services.fastapi.targetPort }}
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.nuxtjs.name }}
  labels:
    app: {{ .Values.services.nuxtjs.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.services.nuxtjs.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.nuxtjs.name }}
    spec:
      containers:
      - name: {{ .Values.services.nuxtjs.name }}
        image: "{{ .Values.image.nuxtjs.repository }}:{{ .Values.image.nuxtjs.tag }}"
        imagePullPolicy: {{ .Values.image.nuxtjs.pullPolicy }}
        ports:
        - containerPort: {{ .Values.services.nuxtjs.targetPort }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configMap.nuxtjs }}
        resources:
          limits:
            cpu: {{ .Values.resources.nuxtjs.limits.cpu }}
            memory: {{ .Values.resources.nuxtjs.limits.memory }}
          requests:
            cpu: {{ .Values.resources.nuxtjs.requests.cpu }}
            memory: {{ .Values.resources.nuxtjs.requests.memory }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.services.nuxtjs.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.services.nuxtjs.targetPort }}
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.postgres.name }}
  labels:
    app: {{ .Values.services.postgres.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.services.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.postgres.name }}
    spec:
      containers:
      - name: {{ .Values.services.postgres.name }}
        image: "{{ .Values.image.postgres.repository }}:{{ .Values.image.postgres.tag }}"
        imagePullPolicy: {{ .Values.image.postgres.pullPolicy }}
        ports:
        - containerPort: {{ .Values.services.postgres.targetPort }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configMap.postgres }}
        resources:
          limits:
            cpu: {{ .Values.resources.postgres.limits.cpu }}
            memory: {{ .Values.resources.postgres.limits.memory }}
          requests:
            cpu: {{ .Values.resources.postgres.requests.cpu }}
            memory: {{ .Values.resources.postgres.requests.memory }}
        volumeMounts:
        - name: {{ .Values.volume.postgres.name }}
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: {{ .Values.volume.postgres.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volume.postgres.claimName }}
