apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.annotations.rewriteTarget }}
    nginx.ingress.kubernetes.io/use-regex: "{{ .Values.ingress.annotations.useRegex }}"
    nginx.ingress.kubernetes.io/proxy-body-size: "{{ .Values.ingress.annotations.proxyBodySize }}"
    nginx.ingress.kubernetes.io/ssl-redirect: "{{ .Values.ingress.annotations.sslRedirect }}"
    cert-manager.io/cluster-issuer: "{{ .Values.ingress.annotations.certManagerIssuer }}"
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls:
  - hosts:
    - {{ .Values.ingress.hosts }}
    secretName: {{ .Values.ingress.tls.secretName }}
  rules:
  - host: {{ .Values.ingress.hosts }}
    http:
      paths:
      - path: /{{ .Values.services.fastapi.name }}(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.services.fastapi.name }}
            port:
              number: {{ .Values.services.fastapi.port }}
      - path: /{{ .Values.services.nuxtjs.name }}(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.services.nuxtjs.name }}
            port:
              number: {{ .Values.services.nuxtjs.port }}
