apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.fastapi.name }}
  labels:
    app: {{ .Values.services.fastapi.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.services.fastapi.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.fastapi.name }}
    spec:
      containers:
      - name: {{ .Values.services.fastapi.name }}
        image: "{{ .Values.image.fastapi.repository }}:{{ .Values.image.fastapi.tag }}"
        imagePullPolicy: {{ .Values.image.fastapi.pullPolicy }}
        ports:
        - containerPort: {{ .Values.services.fastapi.targetPort }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.services.fastapi.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.services.fastapi.targetPort }}
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.streamlit.name }}
  labels:
    app: {{ .Values.services.streamlit.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.services.streamlit.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.streamlit.name }}
    spec:
      containers:
      - name: {{ .Values.services.streamlit.name }}
        image: "{{ .Values.image.streamlit.repository }}:{{ .Values.image.streamlit.tag }}"
        imagePullPolicy: {{ .Values.image.streamlit.pullPolicy }}
        ports:
        - containerPort: {{ .Values.services.streamlit.targetPort }}
        env:
        - name: FASTAPI_ENDPOINT
          value: "http://{{ .Values.services.fastapi.name }}:{{ .Values.services.fastapi.port }}"
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.services.streamlit.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.services.streamlit.targetPort }}
          initialDelaySeconds: 15
          periodSeconds: 20
