[client]
showSidebarNavigation = false

[server]
port = 8501

[theme]
font="sans serif" # "sans serif", "serif", "monospace"
base="dark" # "light", "dark"
primaryColor="#F63366" # "#F63366", blue, Any CSS color, RGB, Hex
# backgroundColor="#FFFFFF"
# secondaryBackgroundColor="#F0F2F6"
# textColor="#262730"