# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  fastapi:
    repository: doantronghieu/vtc-llm-fastapi
    tag: latest
    pullPolicy: Always # IfNotPresent, Always
  streamlit:
    repository: doantronghieu/vtc-llm-streamlit
    tag: latest
    pullPolicy: Always
  postgres:
    repository: doantronghieu/vtc-llm-postgresql
    tag: latest
    pullPolicy: Always

resources:
  fastapi:
    limits:
      cpu: "3" # 1000m = 1cpu, or "1"
      memory: "8Gi"
    requests:
      cpu: "1"
      memory: "1Gi" # Mi, Gi
  streamlit:
    limits:
      cpu: "1"
      memory: "8Gi"
    requests:
      cpu: "1"
      memory: "1Gi"
  postgres:
    limits:
      cpu: "1"
      memory: "2Gi"
    requests:
      cpu: "0.5"
      memory: "1Gi"

services:
  fastapi:
    name: fastapi
    type: ClusterIP
    port: 80
    targetPort: 8000
  streamlit:
    name: streamlit
    type: LoadBalancer
    port: 80
    targetPort: 8051
    externalTrafficPolicy: Cluster
  postgres:
    name: postgres
    type: ClusterIP
    port: 5432
    targetPort: 5432

ingress:
  name: my-ingress
  enabled: true
  annotations:
    rewriteTarget: /${2}
    useRegex: "true"
    proxyBodySize: "50m"
    sslRedirect: "true"
    certManagerIssuer: "letsencrypt-prod"
  hosts: my-domain.com
  tls:
    secretName: my-domain-tls
  ingressClassName: nginx

hpa:
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization: 80
  memoryUtilization: 80

configMap:
  fastapi: fastapi-config
  streamlit: streamlit-config
  postgres: postgres-config

volume:
  postgres:
    name: postgres-data
    storage: 2Gi
    accessModes: ReadWriteMany
    claimName: postgres-pvc
    storageClassName: gp3
    source:
      name: postgres-pv
      hostPath: /mnt/data
