# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  fastapi:
    repository: doantronghieu/llm-fastapi
    tag: amd64
    pullPolicy: Always # IfNotPresent, Always
  streamlit:
    repository: doantronghieu/llm-streamlit
    tag: amd64
    pullPolicy: Always

resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "500m"
    memory: "500Mi"

services:
  fastapi:
    name: fastapi
    type: ClusterIP
    port: 80
    targetPort: 8000
  streamlit:
    name: streamlit
    type: LoadBalancer
    port: 80
    targetPort: 8051
    externalTrafficPolicy: Cluster

ingress:
  name: my-ingress
  enabled: true
  annotations:
    rewriteTarget: /${2}
    useRegex: "true"
    proxyBodySize: "50m"
    sslRedirect: "true"
    certManagerIssuer: "letsencrypt-prod"
  hosts: my-domain.com
  tls:
    secretName: my-domain-tls
  ingressClassName: nginx

hpa:
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization: 80
  memoryUtilization: 80
