# Build stage
FROM python:3.11-slim as build

# Set the working directory
WORKDIR /Apps

# Install system packages
RUN apt-get update && apt-get install -y \
  gcc \
  python3-dev \
  libssl-dev && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# Create a virtual environment
RUN python3 -m venv /opt/venv

# Activate the virtual environment
ENV PATH="/opt/venv/bin:$PATH"

# Copy the requirements file and install dependencies
COPY requirements/prod-LangChain.txt .
RUN pip install --no-cache-dir -r prod-LangChain.txt

# Copy the application code (local -> container)
COPY . .

# Production stage
FROM python:3.11-slim

# Set the working directory
WORKDIR /Apps

# Install system packages
RUN apt-get update && apt-get install -y \
  libssl-dev && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# Copy the virtual environment from the build stage
COPY --from=build /opt/venv /opt/venv

# Activate the virtual environment
ENV PATH="/opt/venv/bin:$PATH"

# Copy the application code from the build stage
COPY --from=build /Apps /Apps

# Create a non-root user for security
RUN adduser --disabled-password --no-create-home app

# Switch to the non-root user and set the PATH environment variable
ENV PATH="/home/app/.local/bin:$PATH"
USER app

# Expose the port (just for documenting)
EXPOSE 8000

# Set the command to run the FastAPI app
WORKDIR /Apps/use_cases/Serve/

CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
