version: '3'
services:
  langchain-streamlit-agent:
    image: langchain-streamlit-agent:latest
    build: ./app
    command: streamlit run streamlit_agent/chat_pandas_df.py --server.port 8051
    volumes:
      - ./streamlit_agent/:/app/streamlit_agent
    ports:
      - 8051:8051