services:
  fastapi:
    image: doantronghieu/llm-fastapi:latest
    container_name: llm-fastapi
    build:
      context: .
      dockerfile: deploy/docker_k8s/docker-files/Dockerfile.fastapi
    ports:
    - "8000:8000"
    networks:
    - app-network
    restart: always
    environment:
    - IN_PROD=True

  streamlit:
    image: doantronghieu/llm-streamlit:latest
    container_name: llm-streamlit
    build:
      context: .
      dockerfile: deploy/docker_k8s/docker-files/Dockerfile.streamlit
    ports:
    - "8051:8051"
    networks:
    - app-network
    restart: always
    environment:
    - ENDPOINT_PROD_FASTAPI=http://fastapi:8000
    - STREAMLIT_GENERAL_CHAT=True
    - STREAMLIT_DATA_DO_ANYTHING=True
    - STREAMLIT_GENERATE_ANYTHING=True
    - STREAMLIT_VTC=True
    depends_on:
    - fastapi

  postgres:
    image: doantronghieu/llm-postgresql:latest
    container_name: postgres
    restart: always
    # shm_size: 128mb # shared memory limit
    volumes:
    - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
    - 5432:5432
    networks:
    - app-network
    # add health check

networks:
  app-network:
    driver: bridge # bridge, overlay
