# Source: helm-chart/templates/config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
data:
  IN_PROD: "true"
---
# Source: helm-chart/templates/config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nuxtjs-config
data:
  IN_PROD: "true"
  ENDPOINT_PROD_FASTAPI: "http://fastapi:80"
---
# Source: helm-chart/templates/config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  IN_PROD: "true"
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: mysecretpassword
  POSTGRES_DB: mydatabase
