apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nuxtjs-to-fastapi
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.services.fastapi.name }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.services.nuxtjs.name }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-fastapi-to-postgres
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.services.postgres.name }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.services.fastapi.name }}