apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.fastapi.name }}
  labels:
    app: {{ .Values.services.fastapi.name }}
spec:
  selector:
    app: {{ .Values.services.fastapi.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.fastapi.port }}
      targetPort: {{ .Values.services.fastapi.targetPort }}
  type: {{ .Values.services.fastapi.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.streamlit.name }}
  labels:
    app: {{ .Values.services.streamlit.name }}
spec:
  selector:
    app: {{ .Values.services.streamlit.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.streamlit.port }}
      targetPort: {{ .Values.services.streamlit.targetPort }}
  type: {{ .Values.services.streamlit.type }}
  externalTrafficPolicy: {{ .Values.services.streamlit.externalTrafficPolicy }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.postgres.name }}
  labels:
    app: {{ .Values.services.postgres.name }}
spec:
  selector:
    app: {{ .Values.services.postgres.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.postgres.port }}
      targetPort: {{ .Values.services.postgres.targetPort }}
  type: {{ .Values.services.postgres.type }}
---
