apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: {{ .Values.volume.postgres.storage }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.volume.postgres.accessModes }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.postgres.claimName }}
spec:
  accessModes:
    - {{ .Values.volume.postgres.accessModes }}
  resources:
    requests:
      storage: {{ .Values.volume.postgres.storage }}
