apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.postgres.claimName }}
spec:
  accessModes:
    - {{ .Values.volume.postgres.accessModes }}
  resources:
    requests:
      storage: {{ .Values.volume.postgres.storage }}
  volumeName: {{ .Values.volume.postgres.source.name }}
  storageClassName: {{ .Values.volume.postgres.storageClassName }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volume.postgres.source.name }}
spec:
  capacity:
    storage: {{ .Values.volume.postgres.storage }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.volume.postgres.accessModes }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.volume.postgres.source.hostPath }}
  storageClassName: {{ .Values.volume.postgres.storageClassName }}
